jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1-node
     steps:
       - checkout
       
       # Restore bundle cache
       - restore_cache:
            keys: 
              #- bundle2-{{ checksum "Gemfile.lock" }}
              - npm3-cache-{{ checksum "package.json" }}

       # Run the bundle install command
       #- run: 
       #   name: Bundle Install
       #   command: bundle install --path vendor/bundle
       
       # Store the bundle cache 
       #- type: cache-save
       #  key: bundle2-{{ checksum "Gemfile.lock" }}
       #  paths:
       #    - vendor/bundle    
       
       # Install NPM
       - run: 
          name: NPM Install
          command: npm install 

       # Save an updated cache of NPM
       - type: cache-save
         key: npm3-cache-{{ checksum "package.json" }}
         paths:
           - node_modules

       - run:
          name: Build Middleman
          command: middleman build

      #  - run:
      #     name: Install OpenJRE
      #     command: sudo apt-get install --assume-yes openjdk-7-jre

      #  - run:
      #     name: Push to S3 and Invalidate
      #     command: s3_website push