jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1-node
     steps:
       - checkout
       
       # Restore bundle cache
       - restore_cache:
            keys: 
              - bundle-{{ checksum "Gemfile.lock" }}

       # Run the bundle install command
       - run: 
          name: Bundle Install
          command: bundle install --path vendor/bundle
       
       # Store the bundle cache 
       - type: cache-save
         key: bundle-{{ checksum "Gemfile.lock" }}
         paths:
           - vendor/bundle    

       # Restore bundle cache
       - restore_cache:
            keys: 
              - npm-cache-{{ checksum "package.json" }}
              - npm-cache-

       # Install NPM
       - run: 
          name: NPM Install
          command: npm install 

       # Save an updated cache of NPM
       - type: cache-save
         key: npm-cache-{{ checksum "package.json" }}
         paths:
           - node_modules

       - run:
          name: Build Middleman
          command: middleman build

       - run:
          name: Install OpenJRE
          command: sudo apt-get install --assume-yes openjdk-7-jre

       - run:
          name: Push to S3 and Invalidate
          command: s3_website push